# fly.toml app configuration file generated for beansearch on 2025-03-17T21:05:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beansearch'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
